### ISSUE TITLE
XCode 9 support

### ISSUE THREAD

**Issue by lishuanglong521** [travisjeffery/ClangFormat-Xcode#132] opened 2018-08-03 09:39 UTC
XCode 9 is not working!!

**Comment by tonyarnold** [comment] 2018-08-03 09:48
Closing as this is a duplicate of #129. This plugin cannot be fixed for Xcode 9 - it doesn't load plugins that aren't signed by Apple anymore.

**Closed by tonyarnold** 2018-08-03 09:48 UTC
